name: Postman CI

on:
    push:
        branches:
            - main

jobs:
    postman-sync:
        name: Sync Postman Collection
        runs-on: ubuntu-latest

        strategy:
            matrix:
                collections:
                    - chain: "arch"
                      service: "node-rpc-api"
                      filename: "openapi.json"
                      collection_id: "25680306-7a02f047-cf8f-4d1d-aefe-fd0f3e950b4c" # Arch - Node RPC API
                    - chain: "bitcoin"
                      service: "blockchain-indexer-api"
                      filename: "openapi.json"
                      collection_id: "25680306-b8148b77-9a7c-4392-a368-2d5acc84b361" # Bitcoin - Blockchain Indexer API
                    - chain: "bitcoin"
                      service: "defi-markets-api"
                      filename: "openapi.json"
                      collection_id: "25680306-dac18a0b-762a-4273-93b2-49246fb08178" # Bitcoin - DeFi Markets API
                    - chain: "bitcoin"
                      service: "event-manager-api"
                      filename: "openapi.json"
                      collection_id: "25680306-1bc9bdd4-4d53-4223-992b-dcd1eaecea0f" # Bitcoin - Event Manager API
                    - chain: "bitcoin"
                      service: "mempool-monitoring-api"
                      filename: "openapi.json"
                      collection_id: "25680306-5687b39d-a712-499f-8301-07db279dc688" # Bitcoin - Mempool Monitoring API
                    - chain: "bitcoin"
                      service: "node-rpc-api"
                      filename: "openapi.json"
                      collection_id: "25680306-ec0dc9e4-d4f1-4ef6-b5db-aeaae88bc49e" # Bitcoin - Node RPC API
                    - chain: "cardano"
                      service: "blockchain-indexer-api"
                      filename: "openapi.json"
                      collection_id: "25680306-45818341-0a26-4bdc-94f0-4655c3818258" # Cardano - Blockchain Indexer API
                    - chain: "cardano"
                      service: "defi-markets-api"
                      filename: "openapi.json"
                      collection_id: "25680306-97bc45c9-8ee3-4492-9474-59a7732ed785" # Cardano - DeFi Markets API
                    - chain: "dogecoin"
                      service: "blockchain-indexer-api"
                      filename: "openapi.json"
                      collection_id: "25680306-d41b4aef-ebf4-4871-a518-bd26795ee65c" # Dogecoin - Blockchain Indexer API
                    - chain: "dogecoin"
                      service: "node-rpc-api"
                      filename: "openapi.json"
                      collection_id: "25680306-e0b01373-b871-4fde-a547-66d3ef99e126" # Dogecoin - Node RPC API
                    - chain: "midnight"
                      service: "indexer-graphql-api"
                      filename: "schema-v1.graphql"
                      collection_id: "25680306-2d91366a-2914-41b2-966c-0fa36b52240f" # Midnight - Indexer GraphQL API

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Update Postman Collection
              env:
                  POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
                  POSTMAN_COLLECTION_ID: "${{ matrix.collections.collection_id }}"
              run: |

                  # Convert and update with error checking
                  RESPONSE=$(curl -s -w "%{http_code}" -X PUT \
                    -H "X-Api-Key: $POSTMAN_API_KEY" \
                    -H "Content-Type: application/json" \
                    -d @${{ matrix.collections.chain }}/${{ matrix.collections.service }}/${{matrix.collections.filename}} \
                    "https://api.getpostman.com/collections/$POSTMAN_COLLECTION_ID")

                  STATUS_CODE=$(echo "$RESPONSE" | tail -n1)
                    if [ "$STATUS_CODE" -ne 200 ]; then
                    echo "Failed to update collection. Status code: $STATUS_CODE"
                    exit 1
                    fi

                  # Convert OpenAPI to Postman collection format
                  curl -X POST \
                      -H "X-Api-Key: $POSTMAN_API_KEY" \
                      -H "Content-Type: application/json" \
                      -d @${{ matrix.collections.chain }}/${{ matrix.collections.service }}/${{matrix.collections.filename}} \
                      "https://api.getpostman.com/collections/$POSTMAN_COLLECTION_ID?format=json" \
                      > collection.json

                  # Update the existing collection
                  curl -X PUT \
                      -H "X-Api-Key: $POSTMAN_API_KEY" \
                      -H "Content-Type: application/json" \
                      -d @collection.json \
                      "https://api.getpostman.com/collections/$POSTMAN_COLLECTION_ID"
