name: Postman CI

on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - dev

jobs:
    postman-sync:
        name: Sync Postman Collection
        runs-on: ubuntu-latest

        strategy:
            matrix:
                collections:
                    - chain: "arch"
                      service: "node-rpc-api"
                      filename: "openapi.json"
                      collection_id: "25680306-fe78d627-7965-4e0b-918e-dbe692199a15" # Arch - Node RPC API
                    - chain: "bitcoin"
                      service: "blockchain-indexer-api"
                      filename: "openapi.json"
                      collection_id: "25680306-2eb301f3-3699-4a6b-85ca-5074ace39abd" # Bitcoin - Blockchain Indexer API
                    - chain: "bitcoin"
                      service: "market-price-api"
                      filename: "openapi.json"
                      collection_id: "25680306-9ee2fc90-71b7-4638-8735-09619168f875" # Bitcoin - Market Price API
                    - chain: "bitcoin"
                      service: "event-manager-api"
                      filename: "openapi.json"
                      collection_id: "25680306-0ac78955-2258-4b4d-a650-794a05059b20" # Bitcoin - Event Manager API
                    - chain: "bitcoin"
                      service: "mempool-monitoring-api"
                      filename: "openapi.json"
                      collection_id: "25680306-9018a8d8-6225-46ab-8a55-212f981dc90e" # Bitcoin - Mempool Monitoring API
                    - chain: "bitcoin"
                      service: "node-rpc-api"
                      filename: "openapi.json"
                      collection_id: "25680306-2b87c393-38ca-491e-a00c-c3ec5a9d1eb7" # Bitcoin - Node RPC API
                    - chain: "bitcoin"
                      service: "wallet-api"
                      filename: "openapi.json"
                      collection_id: "43394706-258357ce-b3ae-4d3e-81f1-63a39502381e" # Bitcoin - Wallet API
                    - chain: "cardano"
                      service: "blockchain-indexer-api"
                      filename: "openapi.json"
                      collection_id: "25680306-11be0660-4aed-463e-8aeb-42b928312ece" # Cardano - Blockchain Indexer API
                    - chain: "cardano"
                      service: "market-price-api"
                      filename: "openapi.json"
                      collection_id: "25680306-06607ddd-ec48-432a-875c-5882168e9d2f" # Cardano - Market Price API
                    - chain: "cardano"
                      service: "managed-contracts-api"
                      filename: "openapi.json"
                      collection_id: "25680306-6fba519e-1528-4c67-a804-4e0f303327bf" # Cardano - Managed Contracts API
                    - chain: "cardano"
                      service: "transaction-manager-api"
                      filename: "openapi.json"
                      collection_id: "25680306-aa2792fb-c80a-4f86-ba70-899fad4aa0f2" # Cardano - Transaction Manager API
                    - chain: "dogecoin"
                      service: "blockchain-indexer-api"
                      filename: "openapi.json"
                      collection_id: "25680306-e37b22b3-b981-4777-a62a-ffb302c7de32" # Dogecoin - Blockchain Indexer API
                    - chain: "dogecoin"
                      service: "node-rpc-api"
                      filename: "openapi.json"
                      collection_id: "25680306-42f880e4-8e29-4453-98d9-3da264ad18c7" # Dogecoin - Node RPC API
                    # - chain: "midnight"
                    #   service: "indexer-graphql-api"
                    #   filename: "schema-v1.graphql"
                    #   collection_id: "25680306-da614c20-571e-4fcc-be24-76b9ec3da8de" # Midnight - Indexer GraphQL API

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            # Install openapi-to-postman converter
            - name: Install Dependencies
              run: npm install -g openapi-to-postmanv2

            - name: Update Postman Collection
              env:
                  POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
                  POSTMAN_COLLECTION_ID: "${{ matrix.collections.collection_id }}"
              run: |
                  bash ./scripts/update_postman_collection.sh ${{ secrets.POSTMAN_API_KEY }} \
                      "${{ matrix.collections.collection_id }}" \
                      "${{ matrix.collections.chain }}" \
                      "${{ matrix.collections.service }}" \
                      "${{ matrix.collections.filename }}"
