name: Postman CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    postman-sync:
        name: Sync Postman Collection
        runs-on: ubuntu-latest

        strategy:
            matrix:
                collections:
                    - chain: "arch"
                      service: "node-rpc-api"
                      filename: "openapi.json"
                      collection_id: "25680306-7a02f047-cf8f-4d1d-aefe-fd0f3e950b4c" # Arch - Node RPC API
                    - chain: "bitcoin"
                      service: "blockchain-indexer-api"
                      filename: "openapi.json"
                      collection_id: "25680306-93b373ad-cb31-40a8-b666-7d45557ed414" # Bitcoin - Blockchain Indexer API
                    - chain: "bitcoin"
                      service: "market-price-api"
                      filename: "openapi.json"
                      collection_id: "39306006-4c68061e-b8bd-4ad7-82a0-147ea3bc1777" # Bitcoin - Market Price API
                    - chain: "bitcoin"
                      service: "event-manager-api"
                      filename: "openapi.json"
                      collection_id: "25680306-1bc9bdd4-4d53-4223-992b-dcd1eaecea0f" # Bitcoin - Event Manager API
                    - chain: "bitcoin"
                      service: "mempool-monitoring-api"
                      filename: "openapi.json"
                      collection_id: "25680306-b671fd32-e3ea-45f3-b10a-6137f509dc65" # Bitcoin - Mempool Monitoring API
                    - chain: "bitcoin"
                      service: "node-rpc-api"
                      filename: "openapi.json"
                      collection_id: "25680306-ec0dc9e4-d4f1-4ef6-b5db-aeaae88bc49e" # Bitcoin - Node RPC API
                    - chain: "cardano"
                      service: "blockchain-indexer-api"
                      filename: "openapi.json"
                      collection_id: "25680306-45818341-0a26-4bdc-94f0-4655c3818258" # Cardano - Blockchain Indexer API
                    - chain: "cardano"
                      service: "market-price-api"
                      filename: "openapi.json"
                      collection_id: "25680306-ac39edad-6eca-4411-b9c4-ac7b0bdbf987" # Cardano - Market Price API
                    - chain: "cardano"
                      service: "managed-contracts-api"
                      filename: "openapi.json"
                      collection_id: "25680306-dfebe48e-adff-4e7f-abac-51ca700b27d1" # Cardano - Managed Contracts API
                    - chain: "cardano"
                      service: "transaction-manager-api"
                      filename: "openapi.json"
                      collection_id: "25680306-1f6ed3e5-f71a-4a37-bf38-3257b4ec3cf3" # Cardano - Transaction Manager API
                    - chain: "dogecoin"
                      service: "blockchain-indexer-api"
                      filename: "openapi.json"
                      collection_id: "25680306-d41b4aef-ebf4-4871-a518-bd26795ee65c" # Dogecoin - Blockchain Indexer API
                    - chain: "dogecoin"
                      service: "node-rpc-api"
                      filename: "openapi.json"
                      collection_id: "25680306-e0b01373-b871-4fde-a547-66d3ef99e126" # Dogecoin - Node RPC API
                    # - chain: "midnight"
                    #   service: "indexer-graphql-api"
                    #   filename: "schema-v1.graphql"
                    #   collection_id: "25680306-2d91366a-2914-41b2-966c-0fa36b52240f" # Midnight - Indexer GraphQL API

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            # Install openapi-to-postman converter
            - name: Install Dependencies
              run: npm install -g openapi-to-postmanv2

            - name: Update Postman Collection
              env:
                  POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
                  POSTMAN_COLLECTION_ID: "${{ matrix.collections.collection_id }}"
              run: |
                  bash ./scripts/update_postman_collection.sh ${{ secrets.POSTMAN_API_KEY }} \
                      "${{ matrix.collections.collection_id }}" \
                      "${{ matrix.collections.chain }}" \
                      "${{ matrix.collections.service }}" \
                      "${{ matrix.collections.filename }}"
